### ISSUE TITLE
Support using enum values in requires

### ISSUE THREAD

**Issue by BenjaminLawson** [google/emboss#67]
It would be nice to be able to use enum values in requires expressions:
```
enum PageScan:
   MIN = 1
   MAX = 100

struct Example:
  0 [+2] PageScan page_scan
    [requires: PageScan.MIN < this < PageScan.MAX] 
```

**Comment by reventlov** [comment]
After thinking about this a bit, I think there are two real options:

1.   Support casts from `enum` types to integer.
2.   Support the full set of comparison operators on `enum`s.

I'm leaning towards option 2, which means moving (the type checks for the `<`, `>`, `<=`, `>=` operators)[https://github.com/google/emboss/blob/master/compiler/front_end/type_check.py#L144] over to the same (function that type checks `==` and `!=`)[https://github.com/google/emboss/blob/master/compiler/front_end/type_check.py#L271].  I *think* that's the only change needed: the way the various comparison operators are implemented in C++ and for inline evaluation should already work with enums.
